# Source: lighthouse/templates/tekton-controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse-tekton-controller
  labels:
    chart: "lighthouse-1.10.10"
    app: lighthouse-tekton-controller
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'lighthouse'
    wave.pusher.com/update-on-config-change: 'true'
  namespace: jx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lighthouse-tekton-controller
  template:
    metadata:
      labels:
        app: lighthouse-tekton-controller
      annotations: {jenkins-x.io/hash: '4f18489e9668e3a1eac07cd8507ea928062fffe79f4eb0d013a1cb719d43e419'}
    spec:
      serviceAccountName: lighthouse-tekton-controller
      containers:
      - name: lighthouse-tekton-controller
        image: ghcr.io/jenkins-x/lighthouse-tekton-controller:1.10.10
        imagePullPolicy: IfNotPresent
        args:
        - --namespace=jx
        - --dashboard-url=http://dashboard-jx.swc.io
        - --dashboard-template=namespaces/{{ .Namespace }}/pipelineruns/{{ .PipelineRun }}
        ports:
        - name: metrics
          containerPort: 8080
        env:
        - name: "LOGRUS_FORMAT"
          value: "json"
        - name: LOGRUS_SERVICE
          value: "lighthouse"
        - name: LOG_LEVEL
          value: "info"
        - name: LOGRUS_SERVICE_VERSION
          value: "1.10.10"
        - name: LOGRUS_STACK_SKIP
          value: ""
        - name: DEFAULT_PIPELINE_RUN_SERVICE_ACCOUNT
          value: "tekton-bot"
        - name: DEFAULT_PIPELINE_RUN_TIMEOUT
          value: "2h0m0s"
        - name: FILE_BROWSER
          value: "git"
        - name: JX_DEFAULT_IMAGE
          value: "ghcr.io/jenkins-x/builder-maven:2.1.149-768"
        - name: LIGHTHOUSE_DASHBOARD_TEMPLATE
          value: "namespaces/{{ .Namespace }}/pipelineruns/{{ .PipelineRun }}"
        - name: LIGHTHOUSE_VERSIONSTREAM_JENKINS_X_JX3_PIPELINE_CATALOG
          value: "cebfcea233cb7955cdf5f99298fb4d7edad8707e"
        envFrom:
        - secretRef:
            name: jx-boot-job-env-vars
            optional: true
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 80m
            memory: 128Mi
      terminationGracePeriodSeconds: 180
      nodeSelector: {}
      affinity: {}
      tolerations: []
